name: nyxx_lavalink_testbot
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
#   path: ^1.8.0
  nyxx: "2.0.0-rc.6"
  nyxx_commander: "2.0.0-rc.10"
  nyxx_lavalink:
    git:
      url: https://github.com/AlvaroMS25/nyxx.git
      ref: dev
      path: nyxx_lavalink/

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0