name: nyxx_lavalink_testbot
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
#   path: ^1.8.0
  nyxx: "^5.0.0"
  logging: "^1.2.0"
  nyxx_commands: "^5.0.0"
  nyxx_lavalink:
    #git: "https://github.com/AlvaroMS25/nyxx_lavalink.git"
    path: "../nyxx_lavalink"

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0